from pathlib import Path

hybrid_path = Path("tkr/hybrid_retrieval.py")
hybrid = hybrid_path.read_text(encoding="utf-8")

old_import = "from .entity_normalization import NORMALIZER_VERSION\n"
new_import = "from .entity_normalization import IdentityLink, NORMALIZER_VERSION, normalize_entities\n"
if old_import not in hybrid:
    raise SystemExit("expected entity_normalization import was not found")
hybrid = hybrid.replace(old_import, new_import, 1)

load_marker = "def _load_jsonl(path: Path, label: str, *, allow_empty: bool = True) -> list[dict[str, object]]:\n"
jsonl_helper = '''def _jsonl_bytes(rows: Sequence[object]) -> bytes:\n    lines: list[str] = []\n    for row in rows:\n        payload = row.to_dict() if hasattr(row, "to_dict") else row\n        lines.append(_canonical_json(payload))\n    return (("\\n".join(lines) + "\\n") if lines else "").encode("utf-8")\n\n\n'''
if load_marker not in hybrid:
    raise SystemExit("expected JSONL loader marker was not found")
hybrid = hybrid.replace(load_marker, jsonl_helper + load_marker, 1)

old_block = '''    artifact_hashes = report.get("artifact_sha256")\n    if not isinstance(artifact_hashes, dict):\n        raise RetrievalError("Phase 4 report is missing artifact hashes")\n    datasets: dict[str, list[dict[str, object]]] = {}\n    for name in _REQUIRED_ARTIFACTS:\n        path = entity_dir / name\n        if not path.is_file():\n            raise RetrievalError(f"missing Phase 4 artifact: {name}")\n        expected = artifact_hashes.get(name)\n        actual = _sha256_bytes(path.read_bytes())\n        if expected != actual:\n            raise RetrievalError(f"artifact SHA-256 mismatch: {name}")\n        datasets[name] = _load_jsonl(path, name)\n\n'''
new_block = '''    artifact_hashes = report.get("artifact_sha256")\n    if not isinstance(artifact_hashes, dict):\n        raise RetrievalError("Phase 4 report is missing artifact hashes")\n    datasets: dict[str, list[dict[str, object]]] = {}\n    artifact_bytes: dict[str, bytes] = {}\n    for name in _REQUIRED_ARTIFACTS:\n        path = entity_dir / name\n        if not path.is_file():\n            raise RetrievalError(f"missing Phase 4 artifact: {name}")\n        data = path.read_bytes()\n        expected = artifact_hashes.get(name)\n        actual = _sha256_bytes(data)\n        if expected != actual:\n            raise RetrievalError(f"artifact SHA-256 mismatch: {name}")\n        artifact_bytes[name] = data\n        datasets[name] = _load_jsonl(path, name)\n\n    # A self-consistent forged report and forged artifacts must not become an\n    # authority boundary. Re-run Phase 4 from the accepted Claims and source,\n    # then require byte-for-byte equality with every published artifact. This\n    # also re-runs current typed Claim validation through normalize_entities().\n    accepted_records = _load_jsonl(accepted_claims_path, "accepted Claim", allow_empty=False)\n    identity_links = (\n        [IdentityLink.from_dict(row) for row in _load_jsonl(identity_path, "identity link", allow_empty=False)]\n        if identity_path is not None\n        else []\n    )\n    regenerated = normalize_entities(\n        accepted_records,\n        source_text,\n        units,\n        identity_links=identity_links,\n    )\n    regenerated_datasets: dict[str, Sequence[object]] = {\n        "mentions.jsonl": regenerated.mentions,\n        "entities.jsonl": regenerated.entities,\n        "facts.jsonl": regenerated.facts,\n        "timeline.jsonl": regenerated.timeline,\n        "conflicts.jsonl": regenerated.conflicts,\n        "ambiguity-groups.jsonl": regenerated.ambiguity_groups,\n    }\n    for name, rows in regenerated_datasets.items():\n        if _jsonl_bytes(rows) != artifact_bytes[name]:\n            raise RetrievalError(f"Phase 4 artifact differs from fresh normalization: {name}")\n    for key, value in regenerated.report.items():\n        if report.get(key) != value:\n            raise RetrievalError(f"Phase 4 report differs from fresh normalization: {key}")\n\n'''
if old_block not in hybrid:
    raise SystemExit("expected Phase 4 artifact verification block was not found")
hybrid = hybrid.replace(old_block, new_block, 1)
hybrid_path.write_text(hybrid, encoding="utf-8")

test_path = Path("tests/test_hybrid_retrieval_adversarial.py")
tests = test_path.read_text(encoding="utf-8")
marker = '\n\nif __name__ == "__main__":\n'
extra_tests = '''\n    def test_forged_artifact_and_rehashed_report_are_rejected(self):\n        with tempfile.TemporaryDirectory() as directory:\n            root = Path(directory)\n            paths = self.basic_project(root)\n            facts_path = paths[3] / "facts.jsonl"\n            row = json.loads(facts_path.read_text(encoding="utf-8"))\n            row["object"] = "火星"\n            forged = json.dumps(row, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\\n"\n            facts_path.write_text(forged, encoding="utf-8")\n            report_path = paths[3] / "entity-normalization-report.json"\n            report = json.loads(report_path.read_text(encoding="utf-8"))\n            from hashlib import sha256\n            report["artifact_sha256"]["facts.jsonl"] = sha256(forged.encode("utf-8")).hexdigest()\n            report_path.write_text(\n                json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\\n",\n                encoding="utf-8",\n            )\n            with self.assertRaises(RetrievalError):\n                build_hybrid_index(*paths[:4], paths[4], identity_links_path=paths[5])\n\n    def test_forged_canonical_permission_in_report_is_rejected(self):\n        with tempfile.TemporaryDirectory() as directory:\n            root = Path(directory)\n            paths = self.make_project(\n                root,\n                ["张三击败李四。", "张三击败王五。"],\n                [\n                    {"unit_index": 1, "evidence": "张三击败李四。", "claim_type": "defeats", "subject": "张三", "object": "李四"},\n                    {"unit_index": 2, "evidence": "张三击败王五。", "claim_type": "defeats", "subject": "张三", "object": "王五"},\n                ],\n            )\n            report_path = paths[3] / "entity-normalization-report.json"\n            report = json.loads(report_path.read_text(encoding="utf-8"))\n            report["may_publish_canonical"] = True\n            report_path.write_text(\n                json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\\n",\n                encoding="utf-8",\n            )\n            with self.assertRaises(RetrievalError):\n                build_hybrid_index(\n                    *paths[:4], paths[4], index_mode="canonical", identity_links_path=paths[5]\n                )\n'''
if marker not in tests:
    raise SystemExit("expected adversarial-test end marker was not found")
tests = tests.replace(marker, extra_tests + marker, 1)
test_path.write_text(tests, encoding="utf-8")
